<a href="https://colab.research.google.com/github/GautamPandit2405/student-performance-analytics/blob/main/notebooks/student_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = [
    [101, "Aarav", "Mathematics", 82, 92, 12],
    [101, "Aarav", "Science", 76, 92, 12],
    [101, "Aarav", "English", 88, 92, 12],
    [102, "Diya", "Mathematics", 91, 97, 15],
    [102, "Diya", "Science", 89, 97, 15],
    [102, "Diya", "English", 93, 97, 15],
    [103, "Kabir", "Mathematics", 65, 78, 7],
    [103, "Kabir", "Science", 70, 78, 7],
    [103, "Kabir", "English", 68, 78, 7],
    [104, "Meera", "Mathematics", 74, 85, 9],
    [104, "Meera", "Science", 81, 85, 9],
    [104, "Meera", "English", 79, 85, 9],
    [105, "Ishaan", "Mathematics", 56, 68, 5],
    [105, "Ishaan", "Science", 61, 68, 5],
    [105, "Ishaan", "English", 59, 68, 5],
    [106, "Anaya", "Mathematics", 87, 94, 13],
    [106, "Anaya", "Science", 90, 94, 13],
    [106, "Anaya", "English", 84, 94, 13],
    [107, "Reyansh", "Mathematics", 72, 82, 8],
    [107, "Reyansh", "Science", 75, 82, 8],
    [107, "Reyansh", "English", 71, 82, 8],
    [108, "Sara", "Mathematics", 95, 98, 16],
    [108, "Sara", "Science", 92, 98, 16],
    [108, "Sara", "English", 96, 98, 16],
]

columns = [
    "student_id", "student_name", "subject",
    "marks", "attendance_pct", "study_hours_week"
]

df = pd.DataFrame(data, columns=columns)

df.to_csv("student_performance.csv", index=False)

print("Dataset created successfully!")
print("Rows and columns:", df.shape)

display(df.head())

Dataset created successfully!
Rows and columns: (24, 6)

,student_id,student_name,subject,marks,attendance_pct,study_hours_week
0,101,Aarav,Mathematics,82,92,12
1,101,Aarav,Science,76,92,12
2,101,Aarav,English,88,92,12
3,102,Diya,Mathematics,91,97,15
4,102,Diya,Science,89,97,15

In [2]:
from google.colab import files

files.download("student_performance.csv")

In [3]:
import pandas as pd

df = pd.read_csv("student_performance.csv")

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Dataset shape: (24, 6)

Column names:
['student_id', 'student_name', 'subject', 'marks', 'attendance_pct', 'study_hours_week']

First 5 rows:

,student_id,student_name,subject,marks,attendance_pct,study_hours_week
0,101,Aarav,Mathematics,82,92,12
1,101,Aarav,Science,76,92,12
2,101,Aarav,English,88,92,12
3,102,Diya,Mathematics,91,97,15
4,102,Diya,Science,89,97,15

Missing values:
student_id          0
student_name        0
subject             0
marks               0
attendance_pct      0
study_hours_week    0
dtype: int64

Duplicate rows: 0

Data types:
student_id           int64
student_name        object
subject             object
marks                int64
attendance_pct       int64
study_hours_week     int64
dtype: object